'use client'

import { useMemo, useState } from 'react'
import {
  AlertCircle, Bell, Check, ChevronDown, ClipboardList, DollarSign, Edit3, Megaphone,
  MoreHorizontal, Phone, Plus, Printer, Receipt, Search, Send, ShieldCheck, Users, X,
} from 'lucide-react'

type Tab = 'fees' | 'students' | 'staff' | 'announcements'
type FeeStatus = 'Paid' | 'Unpaid' | 'Partial' | 'Overdue'

const fees = [
  { name: 'Ayesha Malik', roll: 'CM-1042', className: 'Class 7-A', fee: 'Rs. 8,500', status: 'Paid' as FeeStatus },
  { name: 'Hassan Ali', roll: 'CM-1088', className: 'Class 5-B', fee: 'Rs. 7,800', status: 'Unpaid' as FeeStatus },
  { name: 'Zainab Ahmed', roll: 'CM-1021', className: 'Class 8-A', fee: 'Rs. 9,200', status: 'Partial' as FeeStatus },
  { name: 'Omar Farooq', roll: 'CM-1150', className: 'Class 4-C', fee: 'Rs. 7,500', status: 'Overdue' as FeeStatus },
  { name: 'Noor Fatima', roll: 'CM-1106', className: 'Class 6-A', fee: 'Rs. 8,100', status: 'Paid' as FeeStatus },
]
const students = [
  ['Ayesha Malik', 'Mr. Imran Malik', '0300 4567890', 'Rs. 8,500'], ['Hassan Ali', 'Mr. Tariq Ali', '0321 3322110', 'Rs. 7,800'],
  ['Zainab Ahmed', 'Mr. Kamran Ahmed', '0333 7778899', 'Rs. 9,200'], ['Omar Farooq', 'Mr. Farooq Khan', '0301 5554433', 'Rs. 7,500'],
]
const staff = [
  { name: 'Ms. Sana Ahmed', role: 'Class 7-A · Mathematics', phone: '0300 1112233', status: 'Checked in', initials: 'SA' },
  { name: 'Mr. Bilal Khan', role: 'Class 5-B · Science', phone: '0321 7788990', status: 'Checked in', initials: 'BK' },
  { name: 'Ms. Hira Shah', role: 'Class 8-A · English', phone: '0333 2244668', status: 'Not checked in', initials: 'HS' },
]

function Stat({ icon: Icon, label, value, detail, tone }: { icon: typeof Users; label: string; value: string; detail: string; tone: string }) {
  return <div className={`rounded-3xl p-5 ${tone}`}><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-500">{label}</span><Icon className="size-5 text-slate-600" /></div><p className="mt-3 text-2xl font-bold tracking-tight text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>
}

export default function AdminDashboard() {
  const [tab, setTab] = useState<Tab>('fees')
  const [feeFilter, setFeeFilter] = useState<'All' | FeeStatus>('All')
  const [query, setQuery] = useState('')
  const [className, setClassName] = useState('All Classes')
  const [showAssign, setShowAssign] = useState(false)
  const [whatsapp, setWhatsapp] = useState(true)
  const [inApp, setInApp] = useState(true)
  const [notice, setNotice] = useState('Rain Emergency Holiday / Summer Vacation')
  const filteredFees = fees.filter((f) => feeFilter === 'All' || f.status === feeFilter)
  const filteredStudents = useMemo(() => students.filter((s) => s.join(' ').toLowerCase().includes(query.toLowerCase())), [query])
  const nav = [{ id: 'fees' as Tab, label: 'Fees & Revenue', icon: Receipt }, { id: 'students' as Tab, label: 'Student Directory', icon: Users }, { id: 'staff' as Tab, label: 'Teachers & Staff', icon: ClipboardList }, { id: 'announcements' as Tab, label: 'Announcements', icon: Megaphone }]
  return <main className="min-h-screen bg-[#fffdf5] text-slate-800">
    <header className="border-b border-slate-200/70 bg-white/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-[#dcfce7] text-emerald-700"><ShieldCheck className="size-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">EduFlow Admin</p><h1 className="font-semibold">The Citizens Model School <span className="text-slate-400">· Campus 1</span></h1></div></div><div className="hidden items-center gap-3 sm:flex"><button className="rounded-2xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold hover:bg-slate-50"><Bell className="mr-2 inline size-4" />Notifications</button><div className="flex size-10 items-center justify-center rounded-full bg-[#fef9c3] font-bold">SA</div></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-emerald-700">Friday, August 28, 2026</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Good morning, School Admin</h2><p className="mt-1 text-slate-500">Here&apos;s what&apos;s happening across your campus today.</p></div><div className="flex flex-wrap gap-2"><button className="rounded-2xl bg-slate-800 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-slate-700"><Plus className="mr-2 inline size-4" />Add New Admission</button><button onClick={() => setTab('announcements')} className="rounded-2xl bg-[#fef9c3] px-4 py-3 text-sm font-semibold hover:bg-yellow-200"><Megaphone className="mr-2 inline size-4" />Create Announcement</button></div></div>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Stat icon={Users} label="Total Enrolled" value="850 Students" detail="Across 24 active classes" tone="bg-[#dcfce7]" /><Stat icon={DollarSign} label="Monthly Fee Recovery" value="92%" detail="Rs. 1,420,000 / 1,540,000" tone="bg-[#fef9c3]" /><Stat icon={Check} label="Today&apos;s Attendance" value="94% Students" detail="98% teachers checked in" tone="bg-white border border-slate-200" /></section>
      <div className="mt-8 flex gap-2 overflow-x-auto rounded-3xl bg-slate-100/70 p-2">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-sm font-semibold transition ${tab === id ? 'bg-white text-emerald-700 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}><Icon className="size-4" />{label}</button>)}</div>
      <section className="mt-5 rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-7">
        {tab === 'fees' && <><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm font-semibold text-emerald-700">August 2026</p><h3 className="mt-1 text-2xl font-bold">Fee Challans & Revenue</h3></div><button className="rounded-2xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-800"><Receipt className="mr-2 inline size-4" />Generate This Month&apos;s Challans</button></div><div className="mt-6 flex flex-wrap gap-2">{(['All', 'Paid', 'Unpaid', 'Partial', 'Overdue'] as const).map((f) => <button key={f} onClick={() => setFeeFilter(f)} className={`rounded-full px-4 py-2 text-sm font-semibold ${feeFilter === f ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-500'}`}>{f}</button>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Student</th><th className="pb-3">Roll No.</th><th className="pb-3">Class / Section</th><th className="pb-3">Monthly Fee</th><th className="pb-3">Status</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{filteredFees.map((f) => <tr key={f.roll} className="border-b border-slate-100 last:border-0"><td className="py-4 font-semibold">{f.name}</td><td className="py-4 font-mono text-slate-500">{f.roll}</td><td className="py-4 text-slate-500">{f.className}</td><td className="py-4 font-semibold">{f.fee}</td><td className="py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${f.status === 'Paid' ? 'bg-emerald-100 text-emerald-700' : f.status === 'Partial' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'}`}>{f.status}</span></td><td className="py-4 text-right"><button title="Print challan" className="mr-2 rounded-xl bg-slate-100 p-2 hover:bg-slate-200"><Printer className="size-4" /></button><button title="Send WhatsApp reminder" className="rounded-xl bg-[#dcfce7] p-2 text-emerald-700 hover:bg-emerald-100"><Send className="size-4" /></button></td></tr>)}</tbody></table></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#fef9c3] p-4"><p className="text-sm text-slate-500">Cash collections</p><p className="mt-1 text-xl font-bold">Rs. 520,000</p><div className="mt-3 h-2 rounded-full bg-white/70"><div className="h-2 w-[37%] rounded-full bg-slate-800" /></div></div><div className="rounded-2xl bg-[#dcfce7] p-4"><p className="text-sm text-slate-500">JazzCash / Easypaisa</p><p className="mt-1 text-xl font-bold">Rs. 900,000</p><div className="mt-3 h-2 rounded-full bg-white/70"><div className="h-2 w-[63%] rounded-full bg-emerald-700" /></div></div></div></>}
        {tab === 'students' && <><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h3 className="text-2xl font-bold">Student & Class Directory</h3><p className="mt-1 text-slate-500">Manage your campus roster and student records.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search student, B-Form, class" className="w-full rounded-2xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-emerald-200 md:w-64" /></div><button className="rounded-2xl border border-slate-200 px-3"><ChevronDown className="size-4" /></button></div></div><div className="mt-6 flex gap-2 overflow-x-auto">{['All Classes', 'Nursery', 'Class 1', 'Class 5', 'Class 7', 'Class 10'].map((c) => <button key={c} onClick={() => setClassName(c)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${className === c ? 'bg-[#dcfce7] text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{c}</button>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Student Name</th><th className="pb-3">Father Name</th><th className="pb-3">Contact No.</th><th className="pb-3">Monthly Fee</th><th className="pb-3 text-right">Manage</th></tr></thead><tbody>{filteredStudents.map((s) => <tr key={s[0]} className="border-b border-slate-100 last:border-0"><td className="py-4 font-semibold">{s[0]}</td><td className="py-4 text-slate-500">{s[1]}</td><td className="py-4 text-slate-500">{s[2]}</td><td className="py-4 font-semibold">{s[3]}</td><td className="py-4 text-right"><button className="rounded-xl p-2 hover:bg-slate-100"><Edit3 className="size-4" /></button><button className="rounded-xl p-2 hover:bg-slate-100"><MoreHorizontal className="size-4" /></button></td></tr>)}</tbody></table></div></>}
        {tab === 'staff' && <><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h3 className="text-2xl font-bold">Teachers & Staff Allocation</h3><p className="mt-1 text-slate-500">See who is teaching what and who is on campus.</p></div><button onClick={() => setShowAssign(true)} className="rounded-2xl bg-slate-800 px-4 py-3 text-sm font-semibold text-white"><Plus className="mr-2 inline size-4" />Assign Teacher to Class</button></div><div className="mt-6 grid gap-4 md:grid-cols-3">{staff.map((member) => <div key={member.name} className="rounded-3xl bg-slate-50 p-5"><div className="flex items-start justify-between"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#fef9c3] font-bold">{member.initials}</div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${member.status === 'Checked in' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-600'}`}>{member.status}</span></div><h4 className="mt-5 font-bold">{member.name}</h4><p className="mt-1 text-sm text-slate-500">{member.role}</p><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Phone className="size-4" />{member.phone}</p></div>)}</div></>}
        {tab === 'announcements' && <><div><p className="text-sm font-semibold text-emerald-700">Keep families informed</p><h3 className="mt-1 text-2xl font-bold">School-wide Announcements</h3><p className="mt-1 text-slate-500">Compose one notice and deliver it across every channel.</p></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><div><label className="text-sm font-semibold">Notice board update</label><textarea value={notice} onChange={(e) => setNotice(e.target.value)} rows={6} className="mt-2 w-full resize-none rounded-2xl border border-slate-200 p-4 outline-none focus:ring-2 focus:ring-emerald-200" /><button className="mt-3 rounded-2xl bg-emerald-700 px-5 py-3 font-semibold text-white"><Send className="mr-2 inline size-4" />Publish announcement</button></div><div className="rounded-3xl bg-[#fef9c3] p-5"><h4 className="font-bold">Broadcast channels</h4><Toggle label="WhatsApp API" enabled={whatsapp} onClick={() => setWhatsapp(!whatsapp)} /><Toggle label="In-App Notice" enabled={inApp} onClick={() => setInApp(!inApp)} /></div></div></>}
      </section>
    </div>
    {showAssign && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-5" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="text-xl font-bold">Assign teacher to class</h3><button onClick={() => setShowAssign(false)} className="rounded-full p-2 hover:bg-slate-100"><X className="size-5" /></button></div><label className="mt-6 block text-sm font-semibold">Teacher<select className="mt-2 w-full rounded-2xl border border-slate-200 p-3"><option>Ms. Hira Shah</option><option>Mr. Bilal Khan</option></select></label><label className="mt-4 block text-sm font-semibold">Class / subject<select className="mt-2 w-full rounded-2xl border border-slate-200 p-3"><option>Class 8-A · English</option><option>Class 6-B · Science</option></select></label><button onClick={() => setShowAssign(false)} className="mt-6 w-full rounded-2xl bg-slate-800 py-3 font-semibold text-white">Save allocation</button></div></div>}
  </main>
}
function Toggle({ label, enabled, onClick }: { label: string; enabled: boolean; onClick: () => void }) { return <button onClick={onClick} className="mt-5 flex w-full items-center justify-between text-sm font-semibold"><span>{label}</span><span className={`flex h-6 w-11 items-center rounded-full p-1 transition ${enabled ? 'bg-emerald-600 justify-end' : 'bg-slate-300 justify-start'}`}><span className="size-4 rounded-full bg-white shadow" /></span></button> }
