'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '@/lib/supabaseClient'
import { AlertCircle, Bell, Check, ChevronDown, ClipboardList, DollarSign, Edit3, Megaphone, MoreHorizontal, Phone, Plus, Printer, Receipt, Search, Send, ShieldCheck, Users, X } from 'lucide-react'

type Tab = 'fees' | 'students' | 'staff' | 'announcements'
type FeeStatus = 'Paid' | 'Unpaid' | 'Partial' | 'Overdue'
type FeeRow = { id?: string; name: string; roll: string; className: string; amount: number; status: FeeStatus; dueDate: string; phone: string; tuition: number; lab: number; late: number; challan: string }

const demoFees: FeeRow[] = [
  { name: 'Ayesha Malik', roll: 'CM-1042', className: 'Class 7-A', amount: 8500, status: 'Paid', dueDate: '2026-08-10', phone: '923004567890', tuition: 7500, lab: 1000, late: 0, challan: 'EF-2608-1042' },
  { name: 'Hassan Ali', roll: 'CM-1088', className: 'Class 5-B', amount: 7800, status: 'Unpaid', dueDate: '2026-08-10', phone: '923213322110', tuition: 7000, lab: 800, late: 0, challan: 'EF-2608-1088' },
  { name: 'Zainab Ahmed', roll: 'CM-1021', className: 'Class 8-A', amount: 9200, status: 'Partial', dueDate: '2026-08-10', phone: '923337778899', tuition: 8000, lab: 1200, late: 0, challan: 'EF-2608-1021' },
  { name: 'Omar Farooq', roll: 'CM-1150', className: 'Class 4-C', amount: 7500, status: 'Overdue', dueDate: '2026-08-10', phone: '923015554433', tuition: 6800, lab: 600, late: 100, challan: 'EF-2608-1150' },
  { name: 'Noor Fatima', roll: 'CM-1106', className: 'Class 6-A', amount: 8100, status: 'Paid', dueDate: '2026-08-10', phone: '923001112233', tuition: 7200, lab: 900, late: 0, challan: 'EF-2608-1106' },
]
const students = [['Ayesha Malik', 'Mr. Imran Malik', '0300 4567890', 8500], ['Hassan Ali', 'Mr. Tariq Ali', '0321 3322110', 7800], ['Zainab Ahmed', 'Mr. Kamran Ahmed', '0333 7778899', 9200], ['Omar Farooq', 'Mr. Farooq Khan', '0301 5554433', 7500]]
const staff = [{ name: 'Ms. Sana Ahmed', role: 'Class 7-A · Mathematics', phone: '0300 1112233', status: 'Checked in', initials: 'SA' }, { name: 'Mr. Bilal Khan', role: 'Class 5-B · Science', phone: '0321 7788990', status: 'Checked in', initials: 'BK' }, { name: 'Ms. Hira Shah', role: 'Class 8-A · English', phone: '0333 2244668', status: 'Not checked in', initials: 'HS' }]

function Stat({ icon: Icon, label, value, detail, tone }: { icon: typeof Users; label: string; value: string; detail: string; tone: string }) { return <div className={`rounded-3xl p-5 ${tone}`}><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-500">{label}</span><Icon className="size-5 text-slate-600" /></div><p className="mt-3 text-2xl font-bold tracking-tight text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div> }

export default function AdminDashboard() {
  const [tab, setTab] = useState<Tab>('fees'), [feeFilter, setFeeFilter] = useState<'All' | FeeStatus>('All'), [query, setQuery] = useState(''), [className, setClassName] = useState('All Classes'), [showAssign, setShowAssign] = useState(false), [whatsapp, setWhatsapp] = useState(true), [inApp, setInApp] = useState(true), [notice, setNotice] = useState('Rain Emergency Holiday / Summer Vacation'), [fees, setFees] = useState<FeeRow[]>(demoFees), [selected, setSelected] = useState<FeeRow | null>(null), [toast, setToast] = useState(''), [loading, setLoading] = useState(false)
  useEffect(() => { let active = true; const load = async () => { const { data } = await supabase.from('fee_invoices').select('id,amount,status,due_date,challan_no,tuition_fee,lab_exam_charges,late_fee,students(full_name,roll_number,class_name,parent_phone)').order('due_date', { ascending: false }); if (active && data?.length) setFees(data.map((row: any) => ({ id: row.id, name: row.students?.full_name ?? 'Student', roll: row.students?.roll_number ?? '—', className: row.students?.class_name ?? '—', amount: Number(row.amount ?? 0), status: row.status ?? 'Unpaid', dueDate: row.due_date, phone: row.students?.parent_phone ?? '', tuition: Number(row.tuition_fee ?? 0), lab: Number(row.lab_exam_charges ?? 0), late: Number(row.late_fee ?? 0), challan: row.challan_no ?? `EF-${row.id}` }))); }; load(); return () => { active = false } }, [])
  useEffect(() => { if (toast) { const id = setTimeout(() => setToast(''), 3500); return () => clearTimeout(id) } }, [toast])
  const filteredFees = fees.filter((f) => feeFilter === 'All' || f.status === feeFilter), filteredStudents = useMemo(() => students.filter((s) => `${s[0]} ${s[1]} ${s[2]} ${s[3]}`.toLowerCase().includes(query.toLowerCase()) && (className === 'All Classes' || String(s[0]).includes(className.replace('Class ', '')))), [query, className])
  const generated = fees.reduce((sum, f) => sum + f.amount, 0), recovered = fees.filter((f) => f.status === 'Paid').reduce((sum, f) => sum + f.amount, 0), pending = generated - recovered
  const notify = (message: string) => setToast(message)
  const whatsappReminder = (fee: FeeRow) => { const text = `Dear Parent, Fee challan for ${fee.name} for the amount of Rs.${fee.amount.toLocaleString()} is due by ${fee.dueDate}. Kindly pay on time.`; window.open(`https://wa.me/${fee.phone.replace(/\D/g, '')}?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer') }
  const generateBatch = async () => { setLoading(true); const due = '2026-09-10'; const records = fees.map((f) => ({ student_id: f.id, amount: f.amount, due_date: due, status: 'Unpaid', challan_no: `EF-2609-${f.roll.replace(/\D/g, '')}` })).filter((r) => r.student_id); const { error } = records.length ? await supabase.from('fee_invoices').upsert(records, { onConflict: 'student_id,due_date' }) : { error: null }; setLoading(false); notify(error ? 'Preview mode: batch challans ready to publish.' : 'Batch challans created successfully for all students!') }
  const nav = [{ id: 'fees' as Tab, label: 'Fees & Revenue', icon: Receipt }, { id: 'students' as Tab, label: 'Student Directory', icon: Users }, { id: 'staff' as Tab, label: 'Teachers & Staff', icon: ClipboardList }, { id: 'announcements' as Tab, label: 'Announcements', icon: Megaphone }]
  return <main className="min-h-screen bg-[#fffdf5] text-slate-800"><style jsx global>{`@media print { body * { visibility: hidden !important } .challan-print, .challan-print * { visibility: visible !important } .challan-print { position: absolute; inset: 0; width: 100%; background: white !important; padding: 16px !important } .no-print { display: none !important } }`}</style>
    <header className="border-b border-slate-200/70 bg-white/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-[#dcfce7] text-emerald-700"><ShieldCheck className="size-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">EduFlow Admin</p><h1 className="font-semibold">The Citizens Model School <span className="text-slate-400">· Campus 1</span></h1></div></div><div className="hidden items-center gap-3 sm:flex"><button className="rounded-2xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold hover:bg-slate-50"><Bell className="mr-2 inline size-4" />Notifications</button><div className="flex size-10 items-center justify-center rounded-full bg-[#fef9c3] font-bold">SA</div></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-emerald-700">Friday, August 28, 2026</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Good morning, School Admin</h2><p className="mt-1 text-slate-500">Here&apos;s what&apos;s happening across your campus today.</p></div><div className="flex flex-wrap gap-2"><button className="rounded-2xl bg-slate-800 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-slate-700"><Plus className="mr-2 inline size-4" />Add New Admission</button><button onClick={() => setTab('announcements')} className="rounded-2xl bg-[#fef9c3] px-4 py-3 text-sm font-semibold hover:bg-yellow-200"><Megaphone className="mr-2 inline size-4" />Create Announcement</button></div></div>
      <section className="grid gap-4 sm:grid-cols-3"><Stat icon={DollarSign} label="Total Fee Generated" value={`Rs. ${generated.toLocaleString()}`} detail="Current invoice register" tone="bg-[#dcfce7]" /><Stat icon={Check} label="Total Amount Recovered" value={`Rs. ${recovered.toLocaleString()}`} detail={`${generated ? Math.round(recovered / generated * 100) : 0}% collection rate`} tone="bg-[#fef9c3]" /><Stat icon={AlertCircle} label="Pending / Overdue Balance" value={`Rs. ${pending.toLocaleString()}`} detail="Needs follow-up" tone="bg-white border border-slate-200" /></section>
      <div className="mt-8 flex gap-2 overflow-x-auto rounded-3xl bg-slate-100/70 p-2">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-sm font-semibold transition ${tab === id ? 'bg-white text-emerald-700 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}><Icon className="size-4" />{label}</button>)}</div>
      <section className="mt-5 rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-7">{tab === 'fees' && <><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm font-semibold text-emerald-700">August 2026</p><h3 className="mt-1 text-2xl font-bold">Fee Challans & Revenue</h3></div><button onClick={generateBatch} disabled={loading} className="rounded-2xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60"><Receipt className="mr-2 inline size-4" />{loading ? 'Creating...' : "Generate This Month's Challans (Batch)"}</button></div><div className="mt-6 flex flex-wrap gap-2">{(['All', 'Paid', 'Unpaid', 'Partial', 'Overdue'] as const).map((f) => <button key={f} onClick={() => setFeeFilter(f)} className={`rounded-full px-4 py-2 text-sm font-semibold ${feeFilter === f ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-500'}`}>{f}</button>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Student</th><th className="pb-3">Roll No.</th><th className="pb-3">Class / Section</th><th className="pb-3">Total Payable</th><th className="pb-3">Status</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{filteredFees.map((f) => <tr key={f.challan} className="border-b border-slate-100 last:border-0"><td className="py-4 font-semibold">{f.name}</td><td className="py-4 font-mono text-slate-500">{f.roll}</td><td className="py-4 text-slate-500">{f.className}</td><td className="py-4 font-semibold">Rs. {f.amount.toLocaleString()}</td><td className="py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${f.status === 'Paid' ? 'bg-emerald-100 text-emerald-700' : f.status === 'Partial' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'}`}>{f.status}</span></td><td className="py-4 text-right"><button onClick={() => setSelected(f)} title="Print Challan" className="mr-2 rounded-xl bg-slate-100 p-2 hover:bg-slate-200"><Printer className="size-4" /></button><button onClick={() => whatsappReminder(f)} title="Send WhatsApp Reminder" className="rounded-xl bg-[#dcfce7] p-2 text-emerald-700 hover:bg-emerald-100"><Send className="size-4" /></button></td></tr>)}</tbody></table></div></>}
        {tab === 'students' && <><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h3 className="text-2xl font-bold">Student & Class Directory</h3><p className="mt-1 text-slate-500">Manage your campus roster and student records.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search student, B-Form, class" className="w-full rounded-2xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-emerald-200 md:w-64" /></div><button className="rounded-2xl border border-slate-200 px-3"><ChevronDown className="size-4" /></button></div></div><div className="mt-6 flex gap-2 overflow-x-auto">{['All Classes', 'Nursery', 'Class 1', 'Class 5', 'Class 7', 'Class 10'].map((c) => <button key={c} onClick={() => setClassName(c)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${className === c ? 'bg-[#dcfce7] text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{c}</button>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Student Name</th><th className="pb-3">Father Name</th><th className="pb-3">Contact No.</th><th className="pb-3">Monthly Fee</th><th className="pb-3 text-right">Manage</th></tr></thead><tbody>{filteredStudents.map((s) => <tr key={String(s[0])} className="border-b border-slate-100 last:border-0"><td className="py-4 font-semibold">{s[0]}</td><td className="py-4 text-slate-500">{s[1]}</td><td className="py-4 text-slate-500">{s[2]}</td><td className="py-4 font-semibold">Rs. {Number(s[3]).toLocaleString()}</td><td className="py-4 text-right"><button className="rounded-xl p-2 hover:bg-slate-100"><Edit3 className="size-4" /></button><button className="rounded-xl p-2 hover:bg-slate-100"><MoreHorizontal className="size-4" /></button></td></tr>)}</tbody></table></div></>}
        {tab === 'staff' && <><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h3 className="text-2xl font-bold">Teachers & Staff Allocation</h3><p className="mt-1 text-slate-500">See who is teaching what and who is on campus.</p></div><button onClick={() => setShowAssign(true)} className="rounded-2xl bg-slate-800 px-4 py-3 text-sm font-semibold text-white"><Plus className="mr-2 inline size-4" />Assign Teacher to Class</button></div><div className="mt-6 grid gap-4 md:grid-cols-3">{staff.map((member) => <div key={member.name} className="rounded-3xl bg-slate-50 p-5"><div className="flex items-start justify-between"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#fef9c3] font-bold">{member.initials}</div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${member.status === 'Checked in' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-600'}`}>{member.status}</span></div><h4 className="mt-5 font-bold">{member.name}</h4><p className="mt-1 text-sm text-slate-500">{member.role}</p><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Phone className="size-4" />{member.phone}</p></div>)}</div></>}
        {tab === 'announcements' && <><div><p className="text-sm font-semibold text-emerald-700">Keep families informed</p><h3 className="mt-1 text-2xl font-bold">School-wide Announcements</h3><p className="mt-1 text-slate-500">Compose one notice and deliver it across every channel.</p></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><div><label className="text-sm font-semibold">Notice board update</label><textarea value={notice} onChange={(e) => setNotice(e.target.value)} rows={6} className="mt-2 w-full resize-none rounded-2xl border border-slate-200 p-4 outline-none focus:ring-2 focus:ring-emerald-200" /><button onClick={() => notify('Announcement published successfully.')} className="mt-3 rounded-2xl bg-emerald-700 px-5 py-3 font-semibold text-white"><Send className="mr-2 inline size-4" />Publish announcement</button></div><div className="rounded-3xl bg-[#fef9c3] p-5"><h4 className="font-bold">Broadcast channels</h4><Toggle label="WhatsApp API" enabled={whatsapp} onClick={() => setWhatsapp(!whatsapp)} /><Toggle label="In-App Notice" enabled={inApp} onClick={() => setInApp(!inApp)} /></div></div></>}
      </section>
    </div>
    {showAssign && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-5" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="text-xl font-bold">Assign teacher to class</h3><button onClick={() => setShowAssign(false)} className="rounded-full p-2 hover:bg-slate-100"><X className="size-5" /></button></div><label className="mt-6 block text-sm font-semibold">Teacher<select className="mt-2 w-full rounded-2xl border border-slate-200 p-3"><option>Ms. Hira Shah</option><option>Mr. Bilal Khan</option></select></label><label className="mt-4 block text-sm font-semibold">Class / subject<select className="mt-2 w-full rounded-2xl border border-slate-200 p-3"><option>Class 8-A · English</option><option>Class 6-B · Science</option></select></label><button onClick={() => setShowAssign(false)} className="mt-6 w-full rounded-2xl bg-slate-800 py-3 font-semibold text-white">Save allocation</button></div></div>}
    {selected && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/40 p-4 md:p-10" role="dialog" aria-modal="true"><div className="challan-print mx-auto max-w-7xl rounded-3xl bg-white p-5 shadow-xl md:p-8"><div className="no-print mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-emerald-700">Printable 3-copy fee voucher</p><h3 className="text-2xl font-bold">{selected.name} · {selected.challan}</h3></div><div className="flex gap-2"><button onClick={() => window.print()} className="rounded-2xl bg-slate-800 px-4 py-3 font-semibold text-white"><Printer className="mr-2 inline size-4" />Print Voucher</button><button onClick={() => setSelected(null)} className="rounded-2xl border border-slate-200 p-3"><X className="size-5" /></button></div></div><div className="grid gap-4 md:grid-cols-3">{['Bank / Cashier Copy', 'School Office Copy', 'Student / Parent Copy'].map((copy) => <div key={copy} className="rounded-2xl border-2 border-dashed border-slate-300 p-5"><p className="text-center text-xs font-bold uppercase tracking-widest text-emerald-700">{copy}</p><div className="mt-5 border-b border-slate-200 pb-4"><h4 className="text-lg font-bold">The Citizens Model School</h4><p className="text-sm text-slate-500">Campus 1 · EduFlow</p></div><div className="space-y-2 py-4 text-sm"><Line label="Challan No" value={selected.challan} /><Line label="Student" value={selected.name} /><Line label="Roll No" value={selected.roll} /><Line label="Class" value={selected.className} /><Line label="Due Date" value={selected.dueDate} /></div><div className="border-t border-slate-200 pt-4 text-sm"><Line label="Tuition Fee" value={`Rs. ${selected.tuition.toLocaleString()}`} /><Line label="Lab / Exam Charges" value={`Rs. ${selected.lab.toLocaleString()}`} /><Line label="Late Fee Fine" value={`Rs. ${selected.late.toLocaleString()}`} /><Line label="Total Payable" value={`Rs. ${selected.amount.toLocaleString()}`} strong /></div><p className="mt-8 text-center text-xs text-slate-400">Please retain this copy for your records.</p></div>)}</div></div></div>}
    {toast && <div role="status" className="fixed bottom-5 right-5 z-[60] flex items-center gap-3 rounded-2xl bg-slate-800 px-5 py-4 text-sm font-semibold text-white shadow-xl"><Check className="size-5 text-emerald-300" />{toast}</div>}
  </main>
}
function Line({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between gap-3 ${strong ? 'mt-3 text-base font-bold' : ''}`}><span className="text-slate-500">{label}</span><span className="text-right">{value}</span></div> }
function Toggle({ label, enabled, onClick }: { label: string; enabled: boolean; onClick: () => void }) { return <button onClick={onClick} className="mt-5 flex w-full items-center justify-between text-sm font-semibold"><span>{label}</span><span className={`flex h-6 w-11 items-center rounded-full p-1 transition ${enabled ? 'bg-emerald-600 justify-end' : 'bg-slate-300 justify-start'}`}><span className="size-4 rounded-full bg-white shadow" /></span></button> }
