'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowLeft, BarChart3, Bell, Building2, Check,
  ChevronDown, Cpu, Eye, KeyRound, Megaphone, Plus, Power, Search, Server,
  ShieldAlert, ShieldCheck, Sparkles, TrendingUp, Users, X, Zap,
} from 'lucide-react'

const schools = [
  { name: 'The Learning House', campus: 'DHA Campus', city: 'Karachi', owner: 'Dr. Ayesha Khan', contact: '+92 300 1234567', admin: 'admin@learninghouse.pk', plan: 'Pro', students: 842, limit: 2500, status: 'Active' },
  { name: 'Roots Millennium School', campus: 'Gulberg Campus', city: 'Lahore', owner: 'Mr. Fahad Malik', contact: '+92 321 9876543', admin: 'admin@rootsmillennium.pk', plan: 'Enterprise', students: 2840, limit: 5000, status: 'Active' },
  { name: 'Bloomfield Academy', campus: 'F-8 Campus', city: 'Islamabad', owner: 'Ms. Sara Ahmed', contact: '+92 333 7654321', admin: 'hello@bloomfield.pk', plan: 'Starter', students: 410, limit: 1000, status: 'Trial' },
  { name: 'Beaconhouse North', campus: 'Model Town', city: 'Lahore', owner: 'Mr. Hamza Ali', contact: '+92 301 4448899', admin: 'admin@beaconhouse.pk', plan: 'Pro', students: 2167, limit: 2500, status: 'Overdue' },
]

const metrics = [
  { label: 'Schools Active', value: '48', icon: Building2, trend: '+12.5%', tone: 'mint' },
  { label: 'Active Students', value: '34,200', icon: Users, trend: '+8.2%', tone: 'yellow' },
  { label: 'Monthly Recurring Revenue', value: 'Rs. 385,000', icon: TrendingUp, trend: '+18.4%', tone: 'mint' },
  { label: 'AI Query Volume', value: '12,400', icon: Cpu, trend: 'Requests this month', tone: 'yellow' },
]

const subscriptionPlans = [
  { name: 'Starter', price: '2,500', limit: 'Up to 1,000 Students', features: ['1-Click Digital Attendance', 'Voice & Text Daily Diaries', 'Teacher Gradebook & Exam Marks Entry', 'Standard Web Portal Access'] },
  { name: 'Pro', price: '5,000', limit: 'Up to 2,500 Students', features: ['Everything in Starter', 'Automated Fee Management & 3-Copy Challan Print', 'Automated Term Exam Marksheets & Report Cards', '1-Click WhatsApp Fee Reminders'] },
  { name: 'Enterprise', price: '12,000', limit: 'Unlimited Students', features: ['Everything in Pro', '24/7 EduFlow Gemini AI Parent Companion', 'Automated WhatsApp Attendance Alerts', 'Multi-Campus Management', 'Full Accounting & Expense Ledger', 'Custom Branded Subdomain / Domain Setup', '24/7 Dedicated Support & On-Demand Add-ons'] },
]

export default function SuperAdminPage() {
  const [tab, setTab] = useState('Schools')
  const [city, setCity] = useState('All cities')
  const [plan, setPlan] = useState('All plans')
  const [query, setQuery] = useState('')
  const [showOnboard, setShowOnboard] = useState(false)
  const [announcement, setAnnouncement] = useState(false)
  const [toast, setToast] = useState('')
  const [notice, setNotice] = useState('')

  const filtered = useMemo(() => schools.filter((school) =>
    (city === 'All cities' || school.city === city) &&
    (plan === 'All plans' || school.plan === plan) &&
    `${school.name} ${school.campus} ${school.owner}`.toLowerCase().includes(query.toLowerCase())
  ), [city, plan, query])

  const action = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      <header className="sticky top-0 z-30 border-b border-white/10 bg-slate-950/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-4 lg:px-8">
          <div className="flex items-center gap-3"><Link href="/login" aria-label="Back to login" className="rounded-xl p-2 text-slate-400 hover:bg-white/10 hover:text-white"><ArrowLeft size={18} /></Link><div className="grid size-10 place-items-center rounded-2xl bg-emerald-200 text-slate-950"><ShieldCheck size={21} /></div><div><p className="font-black tracking-tight">EduFlow</p><p className="hidden text-xs text-slate-400 sm:block">Platform Central Control</p></div></div>
          <div className="hidden items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-2 text-xs font-bold text-emerald-200 sm:flex"><span className="size-2 rounded-full bg-emerald-300 shadow-[0_0_12px_#86efac]" /> God Mode secured</div>
          <button onClick={() => action('Security settings opened')} className="rounded-xl border border-white/10 p-2 text-slate-400 hover:bg-white/10 hover:text-white"><KeyRound size={18} /></button>
        </div>
      </header>

      <div className="mx-auto max-w-[1500px] px-5 py-8 lg:px-8 lg:py-12">
        <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.22em] text-emerald-300">Restricted control plane</p><h1 className="text-balance text-3xl font-black tracking-[-0.04em] sm:text-5xl">Platform Central Control <span className="text-emerald-300">(God Mode)</span></h1><p className="mt-3 max-w-2xl leading-7 text-slate-400">One calm command center for every school, student, subscription, and AI workflow across EduFlow.</p></div><button onClick={() => setShowOnboard(true)} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-200 px-5 py-3 text-sm font-black text-slate-950 transition hover:bg-emerald-100"><Plus size={17} /> Onboard new school</button></div>

        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon, trend, tone }) => <article key={label} className="rounded-3xl border border-white/10 bg-slate-900 p-5 shadow-2xl shadow-black/10"><div className="mb-7 flex items-center justify-between"><div className={`grid size-11 place-items-center rounded-2xl ${tone === 'mint' ? 'bg-emerald-200 text-slate-950' : 'bg-yellow-100 text-slate-950'}`}><Icon size={20} /></div><span className="text-xs font-bold text-emerald-300">{trend.startsWith('+') ? trend : 'Live'}</span></div><p className="text-2xl font-black tracking-tight">{value}</p><p className="mt-1 text-sm text-slate-400">{label}</p></article>)}</section>

        <section className="mt-8 rounded-3xl border border-white/10 bg-slate-900 p-6"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-300">Subscription plans</p><h2 className="mt-1 text-2xl font-black">Pakistani market pricing</h2></div><p className="hidden text-sm text-slate-400 sm:block">Manage the plans available to every school.</p></div><div className="grid gap-4 lg:grid-cols-3">{subscriptionPlans.map((tier, index) => <article key={tier.name} className={`rounded-2xl border p-5 ${index === 1 ? 'border-emerald-300/40 bg-emerald-200/10' : 'border-white/10 bg-slate-950/50'}`}><div className="flex items-center justify-between"><h3 className="text-lg font-black">{tier.name}</h3>{index === 1 && <span className="rounded-full bg-yellow-100 px-2 py-1 text-[10px] font-black uppercase text-slate-950">Most popular</span>}</div><p className="mt-4 text-3xl font-black">Rs. {tier.price}<span className="text-sm font-medium text-slate-500"> / month</span></p><p className="mt-2 text-sm font-bold text-emerald-300">{tier.limit}</p><ul className="mt-4 space-y-2 text-sm text-slate-300">{tier.features.map((feature) => <li key={feature} className="flex gap-2"><Check size={15} className="mt-0.5 shrink-0 text-emerald-300" />{feature}</li>)}</ul><button onClick={() => action(`${tier.name} plan selected`)} className="mt-5 w-full rounded-xl bg-emerald-200 px-4 py-2.5 text-sm font-black text-slate-950 hover:bg-emerald-100">Upgrade plan</button></article>)}</div></section>

        <nav className="mt-10 flex gap-2 overflow-x-auto border-b border-white/10 pb-3" aria-label="Admin sections">{['Schools', 'System health', 'Broadcast'].map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold transition ${tab === item ? 'bg-emerald-200 text-slate-950' : 'text-slate-400 hover:bg-white/10 hover:text-white'}`}>{item}</button>)}</nav>

        {tab === 'Schools' && <section className="mt-6"><div className="mb-5 flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-2xl font-black">School management</h2><p className="mt-1 text-sm text-slate-400">{filtered.length} schools matching your filters</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search schools" className="w-48 rounded-xl border border-white/10 bg-slate-900 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-emerald-300" /></label><select value={city} onChange={(e) => setCity(e.target.value)} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-sm"><option>All cities</option><option>Karachi</option><option>Lahore</option><option>Islamabad</option></select><select value={plan} onChange={(e) => setPlan(e.target.value)} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-sm"><option>All plans</option><option>Starter</option><option>Pro</option><option>Enterprise</option></select></div></div>
          <div className="overflow-hidden rounded-3xl border border-white/10 bg-slate-900"><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[0.03] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">School & campus</th><th className="px-5 py-4">Owner contact</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Students</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Actions</th></tr></thead><tbody className="divide-y divide-white/10">{filtered.map((school) => <tr key={school.name} className="transition hover:bg-white/[0.03]"><td className="px-5 py-4"><p className="font-bold">{school.name}</p><p className="mt-1 text-xs text-slate-500">{school.campus} · {school.city}</p></td><td className="px-5 py-4"><p className="font-medium">{school.owner}</p><p className="mt-1 text-xs text-slate-500">{school.admin}</p></td><td className="px-5 py-4"><span className="rounded-full bg-emerald-200/15 px-3 py-1 text-xs font-bold text-emerald-200">{school.plan} · Rs. {school.plan === 'Starter' ? '2.5k' : school.plan === 'Pro' ? '5k' : '12k'}</span></td><td className="px-5 py-4"><p className="font-bold">{school.students.toLocaleString()} <span className="font-normal text-slate-500">/ {school.limit.toLocaleString()}</span></p><div className="mt-2 h-1.5 w-28 rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-300" style={{ width: `${Math.min(100, school.students / school.limit * 100)}%` }} /></div></td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${school.status === 'Active' ? 'bg-emerald-200/15 text-emerald-200' : school.status === 'Trial' ? 'bg-yellow-100/15 text-yellow-100' : 'bg-red-300/15 text-red-200'}`}>{school.status}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => action(`Inspecting ${school.name}`)} aria-label={`Inspect ${school.name}`} className="rounded-lg border border-white/10 p-2 text-slate-300 hover:bg-white/10"><Eye size={15} /></button><button onClick={() => action(`${school.name} upgrade flow opened`)} aria-label={`Upgrade ${school.name}`} className="rounded-lg border border-white/10 p-2 text-emerald-200 hover:bg-emerald-200/10"><TrendingUp size={15} /></button><button onClick={() => action(`${school.name} deactivation flow opened`)} aria-label={`Deactivate ${school.name}`} className="rounded-lg border border-white/10 p-2 text-red-200 hover:bg-red-300/10"><Power size={15} /></button></div></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="p-10 text-center text-slate-400">No schools match those filters.</div>}</div></section>}

        {tab === 'System health' && <section className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><div className="rounded-3xl border border-white/10 bg-slate-900 p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-2xl font-black">System health</h2><p className="mt-1 text-sm text-slate-400">Resource usage across the platform</p></div><span className="inline-flex items-center gap-2 text-xs font-bold text-emerald-300"><Activity size={15} /> All systems operational</span></div>{[['Google AI Studio tokens', '68%', '6.8M / 10M tokens', 'bg-emerald-300'], ['Supabase audio storage', '42%', '42 GB / 100 GB', 'bg-yellow-100'], ['WhatsApp SMS gateway', '81%', 'Rs. 8,100 balance remaining', 'bg-emerald-300']].map(([name, percent, detail, color]) => <div key={name} className="mb-6 last:mb-0"><div className="mb-2 flex justify-between text-sm"><span className="font-bold">{name}</span><span className="text-slate-400">{detail}</span></div><div className="h-3 rounded-full bg-slate-800"><div className={`h-full rounded-full ${color}`} style={{ width: percent }} /></div></div>)}</div><div className="rounded-3xl border border-white/10 bg-slate-900 p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black">Webhook error log</h2><p className="mt-1 text-sm text-slate-400">Latest failed deliveries requiring review</p></div><button onClick={() => action('Error log refreshed')} className="rounded-xl border border-white/10 p-2 text-slate-400 hover:text-white"><Activity size={16} /></button></div>{['WhatsApp delivery · School #024', 'Billing webhook · School #011', 'AI usage sync · School #031'].map((error, i) => <div key={error} className="flex items-center justify-between border-t border-white/10 py-3 text-sm"><span className="flex items-center gap-2 text-slate-300"><AlertTriangle size={15} className="text-yellow-100" />{error}</span><span className="text-xs text-slate-500">{i + 1}h ago</span></div>)}</div></div><div className="rounded-3xl border border-emerald-300/20 bg-emerald-200/10 p-6"><div className="grid size-12 place-items-center rounded-2xl bg-emerald-200 text-slate-950"><Server size={21} /></div><h2 className="mt-5 text-xl font-black">Infrastructure status</h2><div className="mt-5 space-y-3 text-sm">{['Database cluster', 'AI gateway', 'Notification workers', 'Storage bucket'].map((item) => <div key={item} className="flex items-center justify-between"><span className="text-slate-300">{item}</span><span className="flex items-center gap-1.5 font-bold text-emerald-200"><Check size={14} /> Healthy</span></div>)}</div></div></section>}

        {tab === 'Broadcast' && <section className="mt-6 grid gap-5 lg:grid-cols-[1fr_.75fr]"><div className="rounded-3xl border border-white/10 bg-slate-900 p-6"><div className="mb-6 flex items-start justify-between"><div><h2 className="text-2xl font-black">Platform broadcast</h2><p className="mt-1 text-sm text-slate-400">Send a banner or maintenance notice to all dashboards.</p></div><Megaphone className="text-emerald-300" /></div><label className="block text-sm font-bold">Announcement title<input className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 font-normal outline-none focus:border-emerald-300" placeholder="e.g. New fee reports are live" /></label><label className="mt-4 block text-sm font-bold">Message<textarea className="mt-2 min-h-32 w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 font-normal outline-none focus:border-emerald-300" placeholder="Write a clear update for school teams..." /></label><div className="mt-4 flex flex-wrap gap-4 text-sm text-slate-300"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked className="accent-emerald-300" /> School dashboards</label><label className="flex items-center gap-2"><input type="checkbox" defaultChecked className="accent-emerald-300" /> Parent portals</label></div><button onClick={() => { setAnnouncement(true); setNotice('Broadcast queued for all active schools.') }} className="mt-6 rounded-2xl bg-emerald-200 px-5 py-3 text-sm font-black text-slate-950 hover:bg-emerald-100"><Bell size={16} className="mr-2 inline" /> Publish broadcast</button>{notice && <p role="status" className="mt-4 text-sm font-bold text-emerald-200">{notice}</p>}</div><div className="rounded-3xl border border-white/10 bg-slate-900 p-6"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Live preview</p><div className="mt-5 rounded-2xl border border-emerald-300/20 bg-emerald-200/10 p-4"><div className="flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-emerald-200 text-slate-950"><Zap size={16} /></div><div><p className="font-bold">New update from EduFlow</p><p className="mt-1 text-sm leading-6 text-slate-300">Your announcement will appear here across selected portals.</p></div></div></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-sm font-bold">Recent broadcasts</p><p className="mt-3 text-sm text-slate-400">Fee challan improvements <span className="float-right text-xs">Yesterday</span></p></div></div></section>}
      </div>

      {toast && <div role="status" className="fixed bottom-5 right-5 z-50 rounded-2xl border border-emerald-300/20 bg-slate-800 px-4 py-3 text-sm font-bold text-emerald-200 shadow-2xl">{toast}</div>}
      {showOnboard && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-5 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="w-full max-w-xl rounded-3xl border border-white/10 bg-slate-900 p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Quick onboarding</p><h2 className="mt-1 text-2xl font-black">Create school owner</h2></div><button onClick={() => setShowOnboard(false)} aria-label="Close onboarding" className="rounded-xl p-2 text-slate-400 hover:bg-white/10 hover:text-white"><X size={19} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{['School name', 'Campus city', 'Owner / principal name', 'Mobile number', 'Initial admin login ID'].map((label) => <label key={label} className="text-sm font-bold">{label}<input className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 font-normal outline-none focus:border-emerald-300" /></label>)}<label className="text-sm font-bold">Selected plan<select className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-3 font-normal"><option>Starter · Rs. 2.5k</option><option>Pro · Rs. 5k</option><option>Enterprise · Rs. 12k</option></select></label></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-white/[0.04] p-3 text-sm text-slate-300"><KeyRound size={17} className="text-emerald-300" /> Temporary password will be generated securely.</div><button onClick={() => { setShowOnboard(false); action('School onboarding draft created') }} className="mt-6 w-full rounded-2xl bg-emerald-200 py-3 font-black text-slate-950 hover:bg-emerald-100">Create owner account</button></div></div>}
    </main>
  )
}
